<?xml version="1.0"?>
<!DOCTYPE portal [
  <!ELEMENT portal (adapter,connector)>
  <!ELEMENT adapter (module,class)>
  <!ELEMENT connector (module,class,(socket?))>
  <!ELEMENT module (#PCDATA)>
  <!ELEMENT class (#PCDATA)>
  <!ELEMENT socket (ip,port,cache)>
  <!ELEMENT ip (#PCDATA)>
  <!ELEMENT port (#PCDATA)>
  <!ELEMENT cache (#PCDATA)>
  <!ATTLIST cache unit (B|KB|MB) "KB">
]>
<portal>
  <adapter>
    <module>lib.adapters</module>
    <class>PortalConnectAdapter</class>
  </adapter>
  <connector>
    <module>Portal</module>
    <class>SocketToServer</class>
    <socket>
      <ip>127.0.0.1</ip>
      <port>3142</port>
      <cache unit="KB">1</cache>
    </socket>
  </connector>
</portal>